#!/bin/bash

# Left click
if [[ "${BLOCK_BUTTON}" -eq 4 ]]; then
  amixer -q sset Capture 5%+
# Middle click
elif [[ "${BLOCK_BUTTON}" -eq 2 ]]; then
  #amixer -q sset Capture toggle
  /usr/bin/pactl set-source-mute 1 toggle;  # PulseAudio
# Right click
elif [[ "${BLOCK_BUTTON}" -eq 5 ]]; then
  amixer -q sset Capture 5%-
elif [[ "${BLOCK_BUTTON}" -eq 3 ]]; then
  /usr/bin/pactl set-source-mute 1 toggle;  # PulseAudio
fi

statusLine=$(amixer get Capture | tail -n 1)
status=$(echo "${statusLine}" | grep -wo "on")
volume=$(echo "${statusLine}" | awk -F ' ' '{print $5}' | tr -d '[]%')

if [[ "${status}" == "on" ]]; then
#  echo "${volume}%"
#  echo "${volume}%"
#  echo ""
    echo " ${volume}%";
    echo \#FF0000;  # Bright red
    exit 33;
else
#  echo "off"
#  echo "off"
#  echo ""
    echo " ${volume}%"
    echo
    echo \#00FF00;  # Bright green
fi

